### ISSUE TITLE
Fejler når man uploader foto

### ISSUE THREAD

**Issue by jrgensen** [nathejk/foto#3]
FYI: Jeg har installeret image på  https://foto.nathejk.dk 

Hvis man glemmer at indtaste i holdnummer kommer der en js fejl - det er ikke muligt at upload flere billeder i streg uden at skulle reloade websiden

Vær opmærksom på at apple telefoner benytter billede formatet `*.HEIC`

**Comment by jrgensen** [comment]
![E985BDC7-C587-499B-A830-F8B6B387024A](https://user-images.githubusercontent.com/411604/190639049-b9979bda-81e1-462e-84d2-46ab9ebe3935.png)

**Comment by fbjerggaard** [comment]
Jeg har ikke lige et iOS device at teste HEIC billeder med - men umiddelbart burde det virke med alle former for filer.

Jeg har lavet lidt validering på om holdnummer er udfyldt inden man får lov at uploade et billede, og nu skulle man også gerne kunne uploade flere billeder i træk
